#################################################
# DO Community Playbooks: Kafka Cluster
#################################################
- hosts: all
  become: yes
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install Docker Compose
      include_tasks: docker-compose/playbook.yml
    - name: Install Kafka Cluster
      include_tasks: kafka-cluster/playbook.yml